### ISSUE TITLE
More space between menu elements in 0.2-1?

### ISSUE THREAD

**Issue by michaldybczak** [psifidotos/applet-window-appmenu#21]
I don't have the comparison but I have a feeling as if after update menu main positions are a bit too wide? Just a little bit, one or few pixels?

Was that changed or am I paranoid? I may get used to it but now it feels a bit off.

Ah, wait. I did find it in old screenshots so I have the comparison:

NEW
![screenshot-2018-11-24-14-15-15](https://user-images.githubusercontent.com/10132958/48968705-86a74280-eff3-11e8-9405-d14fbdb703b4.png)

OLD
![screenshot-2018-11-24-14-15-27](https://user-images.githubusercontent.com/10132958/48968706-89099c80-eff3-11e8-9a15-7b95f1440df6.png)

I liked the old spacing much better and more consitent to what were used to in applications.

By the way, nice new effect when the menu is too long:
![screenshot-2018-11-24-14-09-54](https://user-images.githubusercontent.com/10132958/48968640-b0139e80-eff2-11e8-8770-161119b578c1.png)

It looks better than overlapping, still some limitation on the size with the ... an effect like in original AWC menu would be good.

**Comment by kupiqu** [comment]
That is hard to compare in the screenshots, but there is space between the different buttons. I don't recall happening this before (neither in plasma's global menu), and I recall having to readjust the title applet to adjust for equal separation wrt the appmenu.

I would prefer not having separation between buttons in appmenu because the buttons margins bring separation themselves, and usually panels have more stuff other than the appmenu, so for applications with large number of menus, these extra space may make things to overlap and look bad.

Ideally, this space between buttons could be removed, or if someone for whatever reason things they are a good thing to have, then give an option to adjust that, so users can set it to 0 if wanted.

**Comment by psifidotos** [comment]
The difference is so small that I wouldn't consider it important. Spacing between menu elements is still units.smallSpacing like before... If anyone can find in the code other reason for the spacing I could look at it

**Comment by kupiqu** [comment]
what do you mean with `If anyone can find in the code other reason for the spacing I could look at it` ?

**Comment by psifidotos** [comment]
Yeah you are right, look at PaintedToolButton there is a property implicit Width, what do you think a good spacing would be for this?

Might be a good idea the GridLayout spacing to make it zero that would help also with Fitts Law and make the button implicit Width to use only one units.smallSpacing and not two

**Comment by kupiqu** [comment]
Yes, please.
