### ISSUE TITLE
Help demand

### ISSUE THREAD

**Issue by N1coc4colA** [psifidotos/applet-window-appmenu#85]
Hello, I'm a young developer. I saw that you're still active on this project. I want to generalize the Global App Menu for Qt Apps and GTK Apps. I'm looking into KDE Global App Menu (this project) and Gnome's one. I develop in C++ with Qt and I think that take your project as a base can be good. So, my question is how are you using the com.canonical.AppMenu.Registrar? I know that is from App Vala Panel project and KDE team ported it to KDE Env. . My problem is that some environments don't support App Vala Panel or haven't the service integrated. I built the service from App Vala Panel but it fails after 5 secs. You're part of KDE team so, I ask you, if you want, to tell me how created the service 'out-of-box' and how to use it (I saw that you have a XCB filtering system).
Thank you for reading if you did it.

**Comment by beojan** [comment]
Just FYI, "demand" doesn't mean the same thing in [English](https://en.wiktionary.org/wiki/demand) as in French. Perhaps [request](https://en.wiktionary.org/wiki/request) is the word you were looking for?

**Comment by psifidotos** [comment]
Some feedback. The plasma team in order to handle the situation has created a service through its plasma-workspace product. Its code can be found at: https://github.com/KDE/plasma-workspace/tree/master/gmenu-dbusmenu-proxy  and probably at: https://github.com/KDE/plasma-workspace/tree/master/libdbusmenuqt

The Plasma developer that implemented and maintains that code is "Kai Uwe Broulik" . The mentioned plasma service is responsible to provide the registered global menus for consumption, e.g. to applets. The global menus applets are using that service in order to access the global menus of specific windows. But for this to happen the apps must have first register theirs menus to that service. Qt and GTK tooltiks are doing this by default I think. 

The current window appmenu applet is just a fork from the plasma original one found at: https://github.com/KDE/plasma-workspace/tree/master/applets/appmenu

So the applets are just requesting menus for specific applications/windows. The xcb part is just used to find the x11 window id in order to be used to access its global menu.

I believe it is better to contact the plasma devs for questions related to the service and improvements for it.

**Comment by N1coc4colA** [comment]
Thank you very much! I'll look after the libraries and some simple apps that are using a dbusmenu export before opening an issue. i think that it'll help me a lot 🙏🙏🙏🙏
